# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=jupyterhub/singleuser:0.7
FROM $BASE_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

# Set when building on Travis so that certain long-running build steps can
# be skipped to shorten build time.
ARG TEST_ONLY_BUILD

USER root

# R pre-requisites
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    fonts-dejavu \
    tzdata \
    gfortran \
    gcc && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID

# R packages including IRKernel which gets installed globally.
RUN conda install --quiet --yes \
    'rpy2=2.9*' \
    'r-base=3.4*' \
    'r-irkernel=0.7*' \
    'r-plyr=1.8*' \
    'r-devtools=1.13*' \
    'r-tidyverse=1.2*' \
    'r-shiny=1.2*' \
    'r-forecast=8.2*' \
    'r-rsqlite=2.1*' \
    'r-reshape2=1.4*' \
    'r-nycflights13=1.0*' \
    'r-caret=6.0*' \
    'r-rcurl=1.95*' \
    'r-crayon=1.3*' \
    'r-randomforest=4.6*' \
    'r-htmltools=0.3*' \
    'r-sparklyr=0.9*' \
    'r-htmlwidgets=1.2*' \
    'r-hexbin=1.27*' && \
    conda clean -tipsy && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

USER root

RUN apt-get update
RUN apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
RUN conda update -n root conda

RUN conda upgrade -n root conda

#RUN conda update --all

RUN apt-get update -y

RUN apt-get install -y libgeos-dev

RUN apt-get purge --auto-remove gdal-bin

RUN apt-get purge --auto-remove libkml-dev

RUN conda install -y -c conda-forge r-rgeos

RUN conda install -y -c conda-forge libnetcdf

RUN conda install -c conda-forge udunits2

RUN conda install -c bioconda sra-tools

RUN conda install -y -c conda-forge r-gmodels

RUN conda install -y -c conda-forge r-seqinr

RUN sudo apt-get install -y libproj-dev libgdal-dev

RUN conda install -y -c bioconda r-proj4

RUN conda install -y -c conda-forge r-sf

RUN conda install -y -c bioconda bioconductor-msa

RUN conda install -y 'r-irkernel=0.7*'

RUN conda install -y 'r-spdep'

RUN conda install -c r r-devtools

RUN conda install -c bioconda r-phytools

RUN conda install -c bioconda r-adegenet
ADD installRLibs.R installRLibs.R
ADD installRLibs.sh installRLibs.sh

RUN bash installRLibs.sh
USER $NB_UID

